#if !canImport(ObjectiveC)
import XCTest

extension Day01Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day01Tests = [
        ("testPart1Example1", testPart1Example1),
        ("testPart1Example2", testPart1Example2),
        ("testPart1Example3", testPart1Example3),
        ("testPart1Example4", testPart1Example4),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example1", testPart2Example1),
        ("testPart2Example2", testPart2Example2),
        ("testPart2Example3", testPart2Example3),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day02Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day02Tests = [
        ("testPart1Example1", testPart1Example1),
        ("testPart1Example2", testPart1Example2),
        ("testPart1Example3", testPart1Example3),
        ("testPart1Example4", testPart1Example4),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day03Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day03Tests = [
        ("testPart1Example1", testPart1Example1),
        ("testPart1Example2", testPart1Example2),
        ("testPart1Example3", testPart1Example3),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example1", testPart2Example1),
        ("testPart2Example2", testPart2Example2),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day04Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day04Tests = [
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day05Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day05Tests = [
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example1", testPart2Example1),
        ("testPart2Example2", testPart2Example2),
        ("testPart2Example3", testPart2Example3),
        ("testPart2Example4", testPart2Example4),
        ("testPart2Example5", testPart2Example5),
        ("testPart2Example6", testPart2Example6),
        ("testPart2Example7", testPart2Example7),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day06Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day06Tests = [
        ("testPart1Example1", testPart1Example1),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example1", testPart2Example1),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day07Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day07Tests = [
        ("testPart1Example1", testPart1Example1),
        ("testPart1Example2", testPart1Example2),
        ("testPart1Example3", testPart1Example3),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example1", testPart2Example1),
        ("testPart2Example2", testPart2Example2),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day08Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day08Tests = [
        ("testPart1Example1", testPart1Example1),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example1", testPart2Example1),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day09Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day09Tests = [
        ("testPart1Example1", testPart1Example1),
        ("testPart1Example2", testPart1Example2),
        ("testPart1Example3", testPart1Example3),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day10Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day10Tests = [
        ("testLineContains", testLineContains),
        ("testLineDoesntContain", testLineDoesntContain),
        ("testPart1Example1", testPart1Example1),
        ("testPart1Example2", testPart1Example2),
        ("testPart1Example3", testPart1Example3),
        ("testPart1Example4", testPart1Example4),
        ("testPart1Example5", testPart1Example5),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example1", testPart2Example1),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day11Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day11Tests = [
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Puzzle", testPart2Puzzle),
        ("testRobot", testRobot),
    ]
}

extension Day12Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day12Tests = [
        ("testPart1Example1", testPart1Example1),
        ("testPart1Example2", testPart1Example2),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example1", testPart2Example1),
        ("testPart2Example2", testPart2Example2),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day13Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day13Tests = [
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day14Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day14Tests = [
        ("testPart1Example1", testPart1Example1),
        ("testPart1Example2", testPart1Example2),
        ("testPart1Example3", testPart1Example3),
        ("testPart1Example4", testPart1Example4),
        ("testPart1Example5", testPart1Example5),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example1", testPart2Example1),
        ("testPart2Example2", testPart2Example2),
        ("testPart2Example3", testPart2Example3),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day15Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day15Tests = [
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day16Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day16Tests = [
        ("testPart1Example1", testPart1Example1),
        ("testPart1Example2", testPart1Example2),
        ("testPart1Example3", testPart1Example3),
        ("testPart1Example4", testPart1Example4),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example1", testPart2Example1),
        ("testPart2Example2", testPart2Example2),
        ("testPart2Example3", testPart2Example3),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day17Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day17Tests = [
        ("testPart1Puzzle", testPart1Puzzle),
    ]
}

extension Day18Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day18Tests = [
        ("testPart1Example1", testPart1Example1),
        ("testPart1Example2", testPart1Example2),
        ("testPart1Example3", testPart1Example3),
        ("testPart1Example4", testPart1Example4),
        ("testPart1Example5", testPart1Example5),
        ("testPart1Puzzle", testPart1Puzzle),
    ]
}

extension Day19Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day19Tests = [
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day20Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day20Tests = [
        ("testPart1Example1", testPart1Example1),
        ("testPart1Example2", testPart1Example2),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example1", testPart2Example1),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day21Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day21Tests = [
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day22Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day22Tests = [
        ("testPart1Example1", testPart1Example1),
        ("testPart1Example2", testPart1Example2),
        ("testPart1Example3", testPart1Example3),
        ("testPart1Example4", testPart1Example4),
        ("testPart1Puzzle", testPart1Puzzle),
    ]
}

extension Day23Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day23Tests = [
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day24Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day24Tests = [
        ("testLocationAdjacency1", testLocationAdjacency1),
        ("testLocationAdjacency2", testLocationAdjacency2),
        ("testLocationAdjacency3", testLocationAdjacency3),
        ("testLocationAdjacency4", testLocationAdjacency4),
        ("testLocationAdjacency5", testLocationAdjacency5),
        ("testLocationAdjacency6", testLocationAdjacency6),
        ("testPart1Example1", testPart1Example1),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example1", testPart2Example1),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Day01Tests.__allTests__Day01Tests),
        testCase(Day02Tests.__allTests__Day02Tests),
        testCase(Day03Tests.__allTests__Day03Tests),
        testCase(Day04Tests.__allTests__Day04Tests),
        testCase(Day05Tests.__allTests__Day05Tests),
        testCase(Day06Tests.__allTests__Day06Tests),
        testCase(Day07Tests.__allTests__Day07Tests),
        testCase(Day08Tests.__allTests__Day08Tests),
        testCase(Day09Tests.__allTests__Day09Tests),
        testCase(Day10Tests.__allTests__Day10Tests),
        testCase(Day11Tests.__allTests__Day11Tests),
        testCase(Day12Tests.__allTests__Day12Tests),
        testCase(Day13Tests.__allTests__Day13Tests),
        testCase(Day14Tests.__allTests__Day14Tests),
        testCase(Day15Tests.__allTests__Day15Tests),
        testCase(Day16Tests.__allTests__Day16Tests),
        testCase(Day17Tests.__allTests__Day17Tests),
        testCase(Day18Tests.__allTests__Day18Tests),
        testCase(Day19Tests.__allTests__Day19Tests),
        testCase(Day20Tests.__allTests__Day20Tests),
        testCase(Day21Tests.__allTests__Day21Tests),
        testCase(Day22Tests.__allTests__Day22Tests),
        testCase(Day23Tests.__allTests__Day23Tests),
        testCase(Day24Tests.__allTests__Day24Tests),
    ]
}
#endif
