#if !canImport(ObjectiveC)
import XCTest

extension Day01Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day01Tests = [
        ("testPart1Example1", testPart1Example1),
        ("testPart1Example2", testPart1Example2),
        ("testPart1Example3", testPart1Example3),
        ("testPart1Example4", testPart1Example4),
        ("testPart1Example5", testPart1Example5),
        ("testPart1Example6", testPart1Example6),
        ("testPart2Example1", testPart2Example1),
        ("testPart2Example2", testPart2Example2),
    ]
}

extension Day02Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day02Tests = [
        ("testPart1Example1", testPart1Example1),
        ("testPart1Example2", testPart1Example2),
        ("testPart2Example1", testPart2Example1),
        ("testPart2Example2", testPart2Example2),
    ]
}

extension Day03Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day03Tests = [
        ("testPart1Example1", testPart1Example1),
        ("testPart1Example2", testPart1Example2),
        ("testPart1Example3", testPart1Example3),
        ("testPart2Example1", testPart2Example1),
        ("testPart2Example2", testPart2Example2),
        ("testPart2Example3", testPart2Example3),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Day01Tests.__allTests__Day01Tests),
        testCase(Day02Tests.__allTests__Day02Tests),
        testCase(Day03Tests.__allTests__Day03Tests),
    ]
}
#endif
