#if !canImport(ObjectiveC)
import XCTest

extension Day01Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day01Tests = [
        ("testPart1Example1", testPart1Example1),
        ("testPart1Example2", testPart1Example2),
        ("testPart1Example3", testPart1Example3),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example1", testPart2Example1),
        ("testPart2Example2", testPart2Example2),
        ("testPart2Example3", testPart2Example3),
        ("testPart2Example4", testPart2Example4),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day02Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day02Tests = [
        ("testPart1Example", testPart1Example),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example", testPart2Example),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day03Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day03Tests = [
        ("testPart1Example1", testPart1Example1),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example1", testPart2Example1),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day04Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day04Tests = [
        ("testPart1Example1", testPart1Example1),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example1", testPart2Example1),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day05Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day05Tests = [
        ("testPart1Example", testPart1Example),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example", testPart2Example),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day06Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day06Tests = [
        ("testPart1Example", testPart1Example),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example", testPart2Example),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day07Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day07Tests = [
        ("testPart1Example", testPart1Example),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example", testPart2Example),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day08Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day08Tests = [
        ("testPart1Example", testPart1Example),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example", testPart2Example),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day09Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day09Tests = [
        ("testPart1Example1", testPart1Example1),
        ("testPart1Example2", testPart1Example2),
        ("testPart1Example3", testPart1Example3),
        ("testPart1Example4", testPart1Example4),
        ("testPart1Example5", testPart1Example5),
        ("testPart1Example6", testPart1Example6),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day10Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day10Tests = [
        ("testPart1Example", testPart1Example),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example", testPart2Example),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day11Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day11Tests = [
        ("testPart1Example", testPart1Example),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Example1", testPart2Example1),
        ("testPart2Example2", testPart2Example2),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

extension Day12Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day12Tests = [
        ("testPart1Example", testPart1Example),
        ("testPart1Puzzle", testPart1Puzzle),
        ("testPart2Puzzle", testPart2Puzzle),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Day01Tests.__allTests__Day01Tests),
        testCase(Day02Tests.__allTests__Day02Tests),
        testCase(Day03Tests.__allTests__Day03Tests),
        testCase(Day04Tests.__allTests__Day04Tests),
        testCase(Day05Tests.__allTests__Day05Tests),
        testCase(Day06Tests.__allTests__Day06Tests),
        testCase(Day07Tests.__allTests__Day07Tests),
        testCase(Day08Tests.__allTests__Day08Tests),
        testCase(Day09Tests.__allTests__Day09Tests),
        testCase(Day10Tests.__allTests__Day10Tests),
        testCase(Day11Tests.__allTests__Day11Tests),
        testCase(Day12Tests.__allTests__Day12Tests),
    ]
}
#endif
