
name: nightlies

on:
  schedule:
    - cron: '0 0 * * * '

jobs:

  linux:
    strategy:
      fail-fast: false
      matrix:
        image:
          - "swift:nightly"
          - "swift:nightly-5.3"
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: swiftlang/${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Swift Version
      run: swift --version
    - name: Build
      run: swift build -c release
    - name: Test
      run: swift test -c release
